######################################################################
# Automatically generated by qmake (3.0) Wed Apr 9 11:53:26 2014
######################################################################

TEMPLATE = app
TARGET = qthello
QT += core gui
QT += widgets
#INCLUDEPATH += .
# Input
SOURCES += main.cpp
